name: Build OpenWrt Docker x86-64 image

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/build.yml"

env:
  FIRMWARE_URL: "https://downloads.openwrt.org/releases/23.05.0-rc4/targets/x86/64/openwrt-23.05.0-rc4-x86-64-generic-squashfs-combined.img.gz"
  REPOSITORY: ilxp/OpenWrt_docker_image
  TAG: 23.05.0-rc4

jobs:
  build:
    name: "Build OpenWrt docker image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Download Firmware
        run: |
          wget $FIRMWARE_URL -O openwrt.tar.gz

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@main
        env:
          FIRMWARE: openwrt.tar.gz
        with:
          name: ${{ env.REPOSITORY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          buildargs: FIRMWARE
          tags: "latest,${{ env.TAG }}"
