name: Build LeS Docker x86-64 image

on:
  workflow_dispatch:
  #schedule:
  # - cron: '35 12 * * SAT'
  #watch:
  # types: [started]
      

env:
  FIRMWARE_URL: "https://github.com/iwrt/iwrt-docker/releases/download/LeS/20231019-iWRT-LeS-Series-x86-64-generic-squashfs-rootfs.img.gz"
  REPOSITORY: iwrt/openwrt-docker  #docker-hub中的用户名以及仓库
  TAG: LeS-x86-64

jobs:
  build:
    name: "Build iwrt docker image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Download Firmware
        run: |
          wget $FIRMWARE_URL -O openwrt.tar.gz

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        env:
          FIRMWARE: openwrt.tar.gz
        with:
          name: ${{ env.REPOSITORY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          buildargs: FIRMWARE
          tags: "latest,${{ env.TAG }}"
